-- ============================================
-- QA Environment Setup
-- Run this as ACCOUNTADMIN against your Snowflake account
-- ============================================

CREATE DATABASE IF NOT EXISTS QA_DB;
CREATE SCHEMA IF NOT EXISTS QA_DB.APP;
CREATE SCHEMA IF NOT EXISTS QA_DB.SCHEMACHANGE;

CREATE TABLE IF NOT EXISTS QA_DB.SCHEMACHANGE.CHANGE_HISTORY (
    VERSION VARCHAR,
    SCRIPT VARCHAR,
    SCRIPT_TYPE VARCHAR,
    CHECKSUM VARCHAR,
    EXECUTION_TIME NUMBER,
    STATUS VARCHAR,
    INSTALLED_BY VARCHAR,
    INSTALLED_ON TIMESTAMP_LTZ
);

GRANT USAGE ON WAREHOUSE CICD_WH TO ROLE CICD_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE QA_DB TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA QA_DB.APP TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA QA_DB.SCHEMACHANGE TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON TABLE QA_DB.SCHEMACHANGE.CHANGE_HISTORY TO ROLE CICD_ROLE;


-- ============================================
-- PROD Environment Setup
-- Run this as ACCOUNTADMIN against your Snowflake account
-- ============================================

CREATE DATABASE IF NOT EXISTS PROD_DB;
CREATE SCHEMA IF NOT EXISTS PROD_DB.APP;
CREATE SCHEMA IF NOT EXISTS PROD_DB.SCHEMACHANGE;

CREATE TABLE IF NOT EXISTS PROD_DB.SCHEMACHANGE.CHANGE_HISTORY (
    VERSION VARCHAR,
    SCRIPT VARCHAR,
    SCRIPT_TYPE VARCHAR,
    CHECKSUM VARCHAR,
    EXECUTION_TIME NUMBER,
    STATUS VARCHAR,
    INSTALLED_BY VARCHAR,
    INSTALLED_ON TIMESTAMP_LTZ
);

GRANT USAGE ON WAREHOUSE CICD_WH TO ROLE CICD_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE PROD_DB TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA PROD_DB.APP TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA PROD_DB.SCHEMACHANGE TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON TABLE PROD_DB.SCHEMACHANGE.CHANGE_HISTORY TO ROLE CICD_ROLE;
