--DEV Account setup 
CREATE ROLE CICD_ROLE;

CREATE USER GITHUB_CICD_USER PASSWORD='Schemachange@pro26#' DEFAULT_ROLE=CICD_ROLE MUST_CHANGE_PASSWORD=FALSE;
GRANT ROLE CICD_ROLE TO USER GITHUB_CICD_USER;  

CREATE WAREHOUSE CICD_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS DEV_DB;
CREATE SCHEMA IF NOT EXISTS DEV_DB.APP;

GRANT USAGE ON WAREHOUSE CICD_WH TO ROLE CICD_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE DEV_DB TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA DEV_DB.APP TO ROLE CICD_ROLE;


'SF_ACCOUNT (e.g., xy12345.region)
SF_USER (e.g., GITHUB_CICD_USER)
SF_PASSWORD
SF_ROLE (e.g., CICD_ROLE)
SF_WAREHOUSE (e.g., CICD_WH)
SF_DB_DEV, SF_DB_QA, SF_DB_PROD (database names)
SF_SCHEMA (e.g., APP)'


CREATE SCHEMA IF NOT EXISTS SCHEMACHANGE;
CREATE TABLE IF NOT EXISTS SCHEMACHANGE.CHANGE_HISTORY (
    VERSION VARCHAR,
    SCRIPT VARCHAR,
    SCRIPT_TYPE VARCHAR,
    CHECKSUM VARCHAR,
    EXECUTION_TIME NUMBER,
    STATUS VARCHAR,
    INSTALLED_BY VARCHAR,
    INSTALLED_ON TIMESTAMP_LTZ
);

GRANT ALL PRIVILEGES ON SCHEMA SCHEMACHANGE TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON TABLE SCHEMACHANGE.CHANGE_HISTORY TO ROLE CICD_ROLE;


CREATE WAREHOUSE CICD_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;



show databases;

select * from DEV_DB.SCHEMACHANGE.CHANGE_HISTORY;