CREATE SCHEMA IF NOT EXISTS {{ env_schema }};

CREATE TABLE IF NOT EXISTS {{ env_schema }}.CUSTOMERS (
    CUSTOMER_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS {{ env_schema }}.ORDERS (
    ORDER_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    ORDER_DATE DATE NOT NULL DEFAULT CURRENT_DATE(),
    TOTAL_AMOUNT NUMBER(12, 2),
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES {{ env_schema }}.CUSTOMERS(CUSTOMER_ID)
);



